/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : FC1.h
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : FreeCntr
**     Version     : Component 01.118, Driver 01.13, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2018-04-09, 16:04, # CodeGen: 35
**     Abstract    :
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
**     Settings    :
**         Timer name                  : TPM1 (16-bit)
**         Compare name                : TPM10
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 16777216 Hz
**           Period
**             Xtal ticks              : 128
**             microseconds            : 3906
**             milliseconds            : 4
**             seconds (real)          : 0.003906190395
**             Hz                      : 256
**           Frequency of counting (Bus clock / prescaler)
**             Hz                      : 16777216
**
**         Initialization:
**              Timer                  : Enabled
**
**         Timer registers
**              Counter                : TPM1CNT   [$0041]
**              Mode                   : TPM1SC    [$0040]
**              Run                    : TPM1SC    [$0040]
**              Prescaler              : TPM1SC    [$0040]
**              Compare                : TPM1C0V   [$0046]
**
**         User handling procedure     : not specified
**     Contents    :
**         Enable          - byte FC1_Enable(void);
**         Disable         - byte FC1_Disable(void);
**         Reset           - byte FC1_Reset(void);
**         GetCounterValue - byte FC1_GetCounterValue(FC1_TTimerValue *Value);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file FC1.h
** @version 01.13
** @brief
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
*/         
/*!
**  @addtogroup FC1_module FC1 module documentation
**  @{
*/         

#ifndef __FC1
#define __FC1

/* MODULE FC1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
/* Include inherited components */
#include "Cpu.h"

/* PUBLISHED CONSTANTS */
#define FC1_COUNTER_INPUT_CLOCK_HZ    0x01000000UL /* Initial counter input clock frequency [Hz] */
#define FC1_PERIOD_VALUE              0xFFFFUL /* Initial period value in ticks of the timer */
#define FC1_PRESCALER_VALUE           0x01U /* Prescaler value of the timer in high speed mode */
#define FC1_TIMER_INPUT_CLOCK         0x01000000UL /* Deprecated, Initial timer input clock value [Hz] */
#define FC1_UP_COUNTER                1 /* The timer counts upwards */
/* High speed mode constants */
#define FC1_COUNTER_INPUT_CLOCK_HZ_HIGH 0x01000000UL /* Counter input clock frequency in high speed mode [Hz] */
#define FC1_PERIOD_VALUE_HIGH         0xFFFFUL /* Period value in ticks of the timer in high speed mode */
#define FC1_PRESCALER_VALUE_HIGH      0x01U /* Prescaler value of the timer in high speed mode */
#define FC1_TIMER_INPUT_CLOCK_HIGH    0x01000000UL /* Deprecated, Initial timer input clock value [Hz] */

typedef word FC1_TTimerValue;          /* Counter or compare value, width depends on timer width */

byte FC1_Enable(void);
/*
** ===================================================================
**     Method      :  FC1_Enable (component FreeCntr)
*/
/*!
**     @brief
**         This method enables the component, i.e. timer is enabled and
**         the internal clocks are counted. The method usually also
**         reset the counter (if it is supported by HW). 
**         The method is not available if the counter is shared.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

byte FC1_Disable(void);
/*
** ===================================================================
**     Method      :  FC1_Disable (component FreeCntr)
*/
/*!
**     @brief
**         This method disables the component, i.e. timer is disabled
**         and the internal clocks are stopped. Last counter value is
**         usually preserved in the counter (if it is supported by HW).
**         The method is not available if the counter is shared.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

#define FC1_Reset() ( \
  TPM1CNTH = 0x00U,                    /* Reset HW Counter */ \
  (byte)ERR_OK                         /* Return result */ \
)
/*
** ===================================================================
**     Method      :  FC1_Reset (component FreeCntr)
*/
/*!
**     @brief
**         This method resets the timer-counter (sets to zero for
**         up-counting HW or to appropriate value for down-counting HW).
**         The method is available only if the counter register can be
**         set by software and the counter is not shared.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

#define FC1_GetCounterValue(Value) ( \
  *(Value) = TPM1CNT,                  /* Set the flag "events disabled" */ \
  (byte)ERR_OK                         /* Return result */ \
)
/*
** ===================================================================
**     Method      :  FC1_GetCounterValue (component FreeCntr)
*/
/*!
**     @brief
**         This method returns a content of the counter.
**     @param
**         Value           - Pointer to returned value.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

void FC1_Init(void);
/*
** ===================================================================
**     Method      :  FC1_Init (component FreeCntr)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END FC1. */

#endif /* ifndef __FC1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
